; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wroom32]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1 
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	madhephaestus/ESP32Servo@^3.0.5
build_flags = 
	-DARDUINO_ARCH_ESP32=1
	-DESP32=1
	-DWROOM32
	;-DUSE_DRIVE_SYSTEM
	-DUSE_EXCAVATION_SYSTEM
build_src_filter = +<*> -<.git/> -<.svn/> +<Sandstorm.cpp>
monitor_speed = 115200