; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32c6]
platform = https://github.com/mnowak32/platform-espressif32.git#boards/seeed_xiao_esp32c6
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip
framework = arduino
board = seeed_xiao_esp32c6
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	madhephaestus/ESP32Servo@^3.0.5
	;madhephaestus/ESP32Encoder@^0.11.7
	paulstoffregen/Encoder@^1.4.4
build_flags = 
	-DARDUINO_ARCH_ESP32=1
	-DESP32=1
	-DUSE_DRIVE_SYSTEM
	-DUSE_TURN_SYSTEM
	-DUSE_DIGGING_SYSTEM
	-DUSE_DEPOSIT_SYSTEM
	-DUSE_CAMERA_SYSTEM
	-DUSE_ENCODER_SYSTEM
build_src_filter = +<*> -<.git/> -<.svn/> +<Sandstorm.cpp>
monitor_speed = 9600
